name = "CreateCraft"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4712c67c3527fe04d9d1fe384ce94bff7ee886579044120ce69ca39145fc9dd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
