name = "CreateCraft - 3.0.0"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2a0318736c08afe7e7e169f6c0ec6373e1e823ceac248c52c634db25e8047ce"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
