name = "CreateCraft"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c53265f662ab1f57c2da5a3dcaee722d5347a0aadfae0f2f91443917436348a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
